export const listFont = [
  'Clip',
  'Bellview',
  'Cotton',
  'Daisy',
  'Garden',
  'Keith',
  'Springfield',
  'LoveL',
  'Photogenic',
  'Selfie',
  'soulja',
  'Venetian',
  'Sacramento-Regular',
  'Alexa ',
  'Amanda ',
  'Amsterdam ',
  'Austin ',
  'Avante ',
  'Barcelona ',
  'Bayview ',
  'Beachfront ',
  'Buttercup ',
  'Chelsea ',
  'ClassicType ',
  'Freehand ',
  'Freespirit ',
  'Greenworld ',
  'LoveNeon ',
  'LoveNote ',
  'Marquee ',
  'Mayfair ',
  'Melbourne ',
  'Monaco ',
  'NeoTokyo ',
  'NeonGlow ',
  'NeonLite ',
  'Neonscript ',
  'Neontrace ',
  'Nevada ',
  'NewCursive ',
  'Northshore ',
  'Rocket ',
  'Royalty ',
  'SciFi ',
  'Signature ',
  'Typewriter ',
  'Vintage ',
  'Waikiki ',
  'WildScript ',
];

// export const fontListPrefix2021 = [
//   'Alexa ',
//   'Amanda ',
//   'Amsterdam ',
//   'Austin ',
//   'Avante ',
//   'Barcelona ',
//   'Bayview ',
//   'Beachfront ',
//   'Buttercup ',
//   'Chelsea ',
//   'ClassicType ',
//   'Freehand ',
//   'Freespirit ',
//   'Greenworld ',
//   'LoveNeon ',
//   'LoveNote ',
//   'Marquee ',
//   'Mayfair ',
//   'Melbourne ',
//   'Monaco ',
//   'NeoTokyo ',
//   'NeonGlow ',
//   'NeonLite ',
//   'Neonscript ',
//   'Neontrace ',
//   'Nevada ',
//   'NewCursive ',
//   'Northshore ',
//   'Rocket ',
//   'Royalty ',
//   'SciFi ',
//   'Signature ',
//   'Typewriter ',
//   'Vintage ',
//   'Waikiki ',
//   'WildScript ',
// ];
