export const listFontColor = [
  'red ',
  'orange ',
  'yellow ',
  'green ',
  'purple ',
  'pink ',
  'white ',
  'blue ',
  'warm-white ',
  'lemon-yellow ',
  'mint ',
  'deep-green ',
  'ice-blue ',
  'tropical-blue ',
  'deep-blue ',
  'cotton-candy ',
  'deep-pink ',
  'light-red ',
];
